"""Menyiapkan lingkungan agar modul di `vendor/` bisa dipakai tanpa diubah.

Empat hal yang dikerjakan, dan HARUS dalam urutan ini:

1. Daftarkan shim `streamlit` ke `sys.modules` — sebelum vendor diimpor.
2. Tambahkan `vendor/` ke `sys.path` — modul vendor saling mengimpor dengan
   nama telanjang (`from komersil_rules import ...`), dan
   `proses_mapping_data_komersil._find_spec_path()` mencari file spec di folder
   skripnya sendiri, jadi xlsx-nya ikut ketemu.
3. Tambal resolusi identitas akun/brand — lihat `pin_identity()`.
4. Selaraskan sequence `id` setelah tulis — lihat `_install_sequence_guard()`.
"""

from __future__ import annotations

import contextlib
import contextvars
import functools
import logging
import os
import re
import sys
from pathlib import Path

_VENDOR = Path(__file__).resolve().parent.parent / "vendor"

_log = logging.getLogger(__name__)

_ready = False


def _load_dev_env() -> None:
    """Di dev lokal, ambil DATABASE_URL dari .env.local repo.

    Di Docker tidak pernah aktif: `env_file` compose sudah menyediakan
    DATABASE_URL, dan `.env.local` memang tidak ikut disalin ke image (Dockerfile
    hanya menyalin `vendor/` dan `app/`). Jadi ini murni kenyamanan `uvicorn`
    langsung dari mesin developer.
    """
    if os.getenv("DATABASE_URL"):
        return
    env_file = Path(__file__).resolve().parents[3] / ".env.local"
    if not env_file.exists():
        return
    pattern = re.compile(r"^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$")
    for line in env_file.read_text(encoding="utf-8", errors="replace").splitlines():
        m = pattern.match(line)
        if not m:
            continue
        value = m.group(2).strip()
        if len(value) >= 2 and value[0] in "\"'" and value[-1] == value[0]:
            value = value[1:-1]
        os.environ.setdefault(m.group(1), value)


def ensure_ready() -> None:
    """Idempoten; aman dipanggil berulang."""
    global _ready
    if _ready:
        return

    _load_dev_env()

    from . import shim

    sys.modules.setdefault("streamlit", shim)

    vendor = str(_VENDOR)
    if vendor not in sys.path:
        sys.path.insert(0, vendor)

    # psycopg2 menghormati variabel libpq. Timescale Cloud mewajibkan TLS,
    # sementara get_postgres_engine_cached() vendor membangun URL tanpa
    # sslmode — jadi kita setel lewat environment, bukan dengan mengedit vendor.
    os.environ.setdefault("PGSSLMODE", "require")

    _install_identity_patch()
    _install_sequence_guard()
    _ready = True


# ── identitas akun & brand ─────────────────────────────────────────────────
# Keputusan desain: Kepiai yang memiliki siklus hidup akun (kuota per platform,
# soft-delete, aturan satu platform satu sumber, upload avatar). Karena itu
# self-heal vendor — yang bisa MEMBUAT baris social_accounts sendiri, lalu jatuh
# ke UUID uuid5 deterministik kalau gagal — dimatikan total. Kalau id-nya tidak
# dikirim, kita berhenti dengan error; jauh lebih baik daripada menulis data ke
# akun hantu yang tak pernah muncul di UI.

_PINNED: contextvars.ContextVar[dict | None] = contextvars.ContextVar(
    "mapping_engine_identity", default=None
)


@contextlib.contextmanager
def pin_identity(accounts: dict[str, str], brand_id: str | None):
    """`accounts` = {platform: social_account_id} untuk batch ini."""
    token = _PINNED.set({
        "accounts": {str(k).strip().lower(): str(v) for k, v in (accounts or {}).items() if v},
        "brand_id": str(brand_id) if brand_id else None,
    })
    try:
        yield
    finally:
        _PINNED.reset(token)


class IdentityNotPinned(ValueError):
    pass


def _install_identity_patch() -> None:
    import komersil_rules

    def _resolve_social_account_id(engine, channel, brand=None, username=None,
                                   platform_user_id=None, org_id=None):
        pinned = _PINNED.get()
        key = str(channel or "").strip().lower()
        sid = (pinned or {}).get("accounts", {}).get(key)
        if not sid:
            raise IdentityNotPinned(
                f"social_account_id untuk platform '{key or '-'}' tidak dikirim. "
                "Akun harus dibuat lebih dulu di Kepiai — mesin ini tidak "
                "membuat akun sendiri."
            )
        return sid

    def _brand_id(engine, brand=None, org_id=None):
        return (_PINNED.get() or {}).get("brand_id")

    komersil_rules._resolve_social_account_id = _resolve_social_account_id
    komersil_rules._brand_id = _brand_id


# ── sequence kolom `id` ────────────────────────────────────────────────────
# MASALAHNYA
#   `upsert_dataframe_to_postgres()` vendor mengisi `id` sendiri dari MAX(id)+1
#   untuk kolom yang dianggapnya "NOT NULL tanpa default". Kolom GENERATED BY
#   DEFAULT AS IDENTITY lolos anggapan itu: di information_schema.columns
#   `column_default`-nya NULL — identitasnya ada di kolom `is_identity`, yang
#   tidak ikut dibaca vendor. Jadi id ditulis eksplisit dan sequence identity
#   tidak pernah maju.
#
# AKIBATNYA MENGENAI PENULIS LAIN, BUKAN IMPOR ITU SENDIRI
#   Impornya sendiri selalu berhasil — MAX(id)+1 memang benar untuk penulis
#   tunggal. Yang jebol adalah dashboard, yang menyimpan atribut post lewat
#   INSERT ... ON CONFLICT (brand_id, post_id) dan mengandalkan identity. Per
#   7 Sep 2026 sequence instagram ada di 7 sementara MAX(id) sudah 105, jadi
#   setiap post yang belum punya baris di l0_extra gagal disimpan dengan
#   duplicate key pada primary key. Post yang sudah punya baris lolos lewat
#   jalur DO UPDATE, itu sebabnya gejalanya tampak muncul per-brand.
#
# KENAPA DITAMBAL DARI SINI
#   `vendor/` salinan verbatim dan tidak boleh diedit (lihat vendor/VENDOR.md),
#   dan blok pengisian id itu ada DI DALAM fungsinya — tidak bisa dicegah dari
#   luar. Yang bisa dilakukan adalah merapikan akibatnya: setelah tulis sukses,
#   dorong sequence ke MAX(id)+1 supaya penulis berikutnya tidak menabrak.
#   Migrasi 051 membereskan data yang sudah terlanjur; guard ini menahan supaya
#   tidak melenceng lagi setiap kali ada impor CSV baru.
#
#   Buang guard ini begitu perbaikan hulu turun — syaratnya `is_identity` ikut
#   dibaca di query metadata vendor dan kolom identity dilewati seperti kolom
#   ber-default. Sampai saat itu, membuangnya berarti error yang sama kembali.

_IDENT_RE = re.compile(r"^[a-z_][a-z0-9_]*$")


def _resync_id_sequence(engine, schema_name, table_name) -> None:
    """Dorong sequence kolom `id` ke MAX(id)+1. Idempoten."""
    if not schema_name or not table_name:
        return
    schema, table = str(schema_name).strip().lower(), str(table_name).strip().lower()
    if not (_IDENT_RE.match(schema) and _IDENT_RE.match(table)):
        return

    from sqlalchemy import text

    with engine.begin() as conn:
        # NULL untuk kolom yang bukan serial/identity — mis. `id` uuid di
        # l0_raw.*, yang tidak punya sequence dan memang tidak perlu disentuh.
        seq = conn.execute(
            text("SELECT pg_get_serial_sequence(:t, 'id')"), {"t": f"{schema}.{table}"}
        ).scalar()
        if not seq:
            return
        # is_called=false → nextval berikutnya mengembalikan tepat nilai ini.
        conn.execute(
            text(
                f'SELECT setval(:seq, COALESCE((SELECT MAX(id) FROM "{schema}"."{table}"), 0) + 1, false)'
            ),
            {"seq": seq},
        )


def _install_sequence_guard() -> None:
    import postgres_addon_komersil as pak

    real_upsert = pak.upsert_dataframe_to_postgres

    @functools.wraps(real_upsert)
    def _upsert_then_resync(df, schema_name=None, table_name=None, **kw):
        result = real_upsert(df, schema_name=schema_name, table_name=table_name, **kw)
        # Gagal menyelaraskan TIDAK boleh membatalkan tulis yang sudah sukses:
        # datanya sudah masuk dan benar, yang tertinggal hanya sequence. Dicatat
        # sebagai warning supaya tetap terlihat kalau mulai sering terjadi.
        try:
            _resync_id_sequence(pak.get_postgres_engine(), schema_name, table_name)
        except Exception as err:   # noqa: BLE001 — sengaja menelan semua
            _log.warning(
                "sequence id %s.%s gagal diselaraskan: %s", schema_name, table_name, err
            )
        return result

    pak.upsert_dataframe_to_postgres = _upsert_then_resync
