-- Up Migration
-- Sequence kolom `id` di l0_extra.*_post_extra_attribute tertinggal jauh di
-- belakang MAX(id), jadi INSERT baris BARU dari dashboard (penandaan pilar di
-- tab Content Pillars) menabrak primary key:
--
--   duplicate key value violates unique constraint
--   "instagram_post_extra_attribute_pkey" | Key (id)=(6) already exists
--
-- Keadaan saat migrasi ini ditulis (7 Sep 2026):
--   instagram_post_extra_attribute  MAX(id)=105, id berikutnya 7
--   facebook_post_extra_attribute   MAX(id)=105, id berikutnya 21
--   tiktok_post_extra_attribute     MAX(id)=36,  id berikutnya 43  ← kebetulan aman
--
-- PENYEBABNYA JALUR IMPOR CSV, BUKAN DASHBOARD
--   upsert_dataframe_to_postgres() di mapping engine mengisi `id` sendiri dari
--   MAX(id)+1 untuk kolom yang dianggapnya "NOT NULL tanpa default". Kolom
--   GENERATED BY DEFAULT AS IDENTITY memang melaporkan column_default = NULL di
--   information_schema — identitasnya ada di kolom is_identity, yang tidak ikut
--   dibaca di sana. Jadi id ditulis eksplisit dan sequence tidak pernah maju.
--   Sisi Kepiai menahannya lewat _install_sequence_guard() di
--   services/mapping-engine/app/bootstrap.py; perbaikan permanennya di hulu.
--
-- KENAPA GEJALANYA TERLIHAT PER-BRAND
--   Post yang SUDAH punya baris di l0_extra kena jalur ON CONFLICT DO UPDATE,
--   arbiternya (brand_id, post_id), sehingga id tidak pernah diminta dan
--   penyimpanan tampak normal. Yang gagal hanya post yang belum pernah ditandai
--   sama sekali — persis kondisi brand yang baru mulai ditandai.
--
-- setval(..., false) membuat nextval berikutnya mengembalikan tepat MAX(id)+1.
-- Idempoten dan aman diulang; untuk tabel kosong mulai dari 1.

SELECT setval(
  pg_get_serial_sequence('l0_extra.instagram_post_extra_attribute', 'id'),
  COALESCE((SELECT MAX(id) FROM l0_extra.instagram_post_extra_attribute), 0) + 1,
  false);

SELECT setval(
  pg_get_serial_sequence('l0_extra.facebook_post_extra_attribute', 'id'),
  COALESCE((SELECT MAX(id) FROM l0_extra.facebook_post_extra_attribute), 0) + 1,
  false);

SELECT setval(
  pg_get_serial_sequence('l0_extra.tiktok_post_extra_attribute', 'id'),
  COALESCE((SELECT MAX(id) FROM l0_extra.tiktok_post_extra_attribute), 0) + 1,
  false);

-- Down Migration
-- Tidak ada. Mengembalikan sequence ke nilai tertinggal berarti sengaja membuat
-- INSERT berikutnya gagal lagi — turun-versi yang tidak punya arti.
